theme: jekyll-theme-minimal
title: whisper
description: 日常囈語
navigation:
  - title: biography
    url: https://zenkarsha.github.io/biography/
  - title: poetry
    url: https://zenkarsha.github.io/poetry/
  - title: muse
    url: https://zenkarsha.github.io/muse/
  - title: whisper
    url: https://zenkarsha.github.io/whisper/
